apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: miha
spec:
  encryptedData:
    discord-token: AgDedmP13HrnzEO0daFyHdYfby51fF53r9HJqddD4gDIU1MKfdMNGtco1YcZkQRG5ww+k4zygstfWs9mNuUgsBSaOmVRlnNDyTI9BpBtbwaIgc6S2U04RjZVYamlDRQqjJKK/N4v2GjbR60nlnjgcFszJ2SQeQjpxIweSHP44JwAcEUVjPOcoogJYV43l9+qibXvu4uslFHIRFtyRy+1c7gBvgA6LDdlLbQPMnIBMYvnYOdEG79l6gKW0tVq23aVbMVwazDvh06bApEx+Eelldj1MrHd2qFqQ0DAt7dFEo/p1FniGhyxUKi+Z3+7mgi5rIilXKTXaJmztAILeJw08ni9h9GA84gBRQb2nQH50W75kKGHn/oppqmSC0fTki/JKlg5OMi3QhquOrG1sspdJtkf7QtZ7B3vbB/KiRD2Bd/qUc424LXqiJRR+yLVe4YJoQfuiyoMJ98yaaGQ89Up0XjzH+djVikk7iJPX0bP8W5yGPoyxWXBXGY2uAHqRRKZih7sy7VqFE3lVaRxTZT/4UP4vrBNY23Fsre4OgPe0NawSxgSh6HGCe8IcUdlpEHJIQ3NjcT+6oxlQ7kcxtRwLfiAZs9rr2diLygvXpG+iAVUrIlMk3wqnPVzW4N5tUVIz33EETiURd/7NiGMrskHq3aAWq3WCQKno3Y7qe65hKohDYHkNN3HbC38yAQ6TySI8y6bwC9ZTWq8WTjrUvgG2Wx9ohX8FiDPe0xG3NSGxAXugskCIJJZcDuSdxsvvzH39OQkvAxZGLfukEPx5nO2oV8yDf3ziSmUpic=
    guild-id: AgAvAaFZnhFVh0mD1gV1tkDVesMjN2+VzazGtMPZoP+kiteL1/OW3hw2J4bNWdJaeLq87uiOvqNmqyD4jFdqfVOz3tsokp8cKYQ4N0CC3t4y51B75tiEAKi69nsBUZZVPilkTIfyiqOffNswcpwr02S4qZxcgy+VBXqHLa6zIfOmxK+NF+2FqOz8CyY1sz3Rp3lGYXXCIsILFeH39qE00LMw0jjo+B1PXeIz/ox8R3ocRlan48al5/RxrX2F4fr8Zvm+v1v1khA4EcOM0LOdA8n56djYODmL/Oyn6FUcOVfwMNuL5Hmn9uGsu7WXh5dXepUzrkDGQXo2GcJzJ9nRJOKlhdlz6DMkx7LvfYb/U3M4UCtZzU1k5tdvFq+dk/kyp/oTvp9igatHexbx12Y56ZauBHV1YcAzwW89ML7zYT1SpBbQboORKi1XggsXfqtRfjphLK39+qtHSK3jqLEZAguSQGZghL/Ab2YobKYW8mH+N5l2VdsEZA6NO/YUAsCbGT7B/w5N+mCnz7ZBeYnRdnBClKnvzVOeJz1Hh47PzgsBBG0G61hF6m9KrANRmIq4kxVzwE+BN7PloKJ2Zhz9dcPD35aWvIOXdvJ02IVOSE+RW0PB7RSMNyY2GbASIm0lCTUnLjn3oDxlGmh2bR0Wi4jzfyWNVy1v8VmvtqbJshxUQNRihWgtLP8Img/yAGcLQa1xcQN2cOTZe4K5LHDmd1M1vBo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: miha
    type: Opaque
