apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: miha
spec:
  encryptedData:
    discord-token: AgAVp9hazNCjRivbtPD2L20b1eRDvG6jMpqFF3zxaRSdKl1uKx38a+QcrMpez3GA1DBzY5RKZpb2vANAPeB05y5UCqDcZML7SwMv8r7YknCNgAnFPe8B2J3bvI2bul99IKV3XwFF1boeuAGQZ2Cd8DG0dZEGcK9l4mruxg2dSqsUjQgZCYu+p2cCTyWZkM+zPXND0bAXakZ+kIE9It0B4I3qYlAhOhlRahu10OHfj4z3jNHa4KjZfHEyvVajhEcmvPHvxvm6irzYTnWl8RT0E06A6z2rFIFiMslezjbvczoqNB/VBQiXUZvxdBt2dGtjJwfOwSAMk13hc980rB8gp72UHh+tVK6TxImrgSRgipzDId780EPdP8Ry4Fn05GhWOjSHLkUgAyNHerAQCecxWgp6EZ9Bwe9XodyR/LmJNP7WrPRT3ZrYKbCvTUFYo06wLjVmGLG4khOD64zrozEWcyZXH3ypM500WsWQhoYd5zuca16BmiIzOt54iHjgS3Doal73YfgsBvBfLSulFHHW9BM24jqJQCfumEcDO1c2rRu7Amcm8/9d89BH79wT6i3tVYT9b/yagPve7B40eJ+kXSgPjNEVVFW6c9nWG3ni+/g3wBvhDCDT76fZk2lTHcNSf9KXtADs+kndDGwP7/WYf1O58rODY3sqdWQgnkLOhu69nN7fRC5xE2OzXUel23+5BP2L5vn93bbwu5f4HMf0q5o25jAm6WrKhLPF/ner5XZRKcZo1OPVijF9wx9gtR8DLbMRVlkW2rxn5dpSjih65qJYyKO3OpMCijI=
    guild-id: AgDlqH7JcjcCRdMuqrBNPO7pYC+lJLWU3XF5s+86dngvmZYaVnO3vWfr2CI8abLgMKGrQgGqz8RUFo6lmKNEUmeU5HBHRmpkMOZe04FzZoVkb+/sQTdPHCuah9KurM5DKTVbU5w8NFRLz4h3lbZr9J+Z/rH0xBJ3Tlcw9SuzLWQIw8y4KcfMSndJ7vAe3UbpcAwR0pEEvHaOp85Pm11Q3IpX5DK5I15AeZvXUeiWwEXAiKbsLABj+Q0JvibZ1yce/pDwZuAYfcUlE/yvCcdtKiNAQ5g2Wvg4+c2m4XFQ0S3sXucSEG2vJbMIgo4tBLJjWFxyOAVLs9Lb45atwlpIiGzWqQeVerQRig9MiCJ4xfXtdmVo87CB6Kb+CLInxiEAiG0e4hq+je583HRWqg2uHK0GCBU+AbxGxRjSgv0g3TM3HA+4yaWrs/FBR8LMcRD3Rfm7sWBva4zG7yNkceARXlLTER6KcIQ4CVYYAz4smfZiyxvpLSXgsA6265kPxVl+UEXpIGs0HJ3CleZN0aD9UweZKB+CbwUtbw48lb2wxmeUwUIrGh5hx5gQQY6lycPPTjNyOxdbh9wphf0/p9YKca/95+Hm9gbWxdyQ6rkhUanaMFSyDQy0cnlKzROT5CszAZXHmGJ04g03NyxP6ip2IPGf2xpbce6LuTVAg/cthk8GAbuGOLw+c3Mzl7Hm2rcFISkruwhtIV7qCWmisbXCzmimb/U=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: miha
    type: Opaque
