apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miha
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    discord-token: AgAjBOAbQd9vWbMQUvO4RJvZXjMLdMqIrPwdu+0f+nUtN/ZJhUJFc2ZNKqlp61/yjLwQvQnYvp6nhKOPqkELius/48g4Llnzzjq7ck/Qyf/6lryvjvJXrQ0YVKdVjkVHbxeZmHY7gpjoSKTrcjgfMZ5DHE5CeKG9sz75iiJkXg1zmqDiYTw7A6vMgVKCxS0p7e9sit7RNjIqTlVK7EBcyLi3dgSXtvxY3pl+hfOufMgyEYuj3v2XzmRumtMDuDjguugq6ZFiDN5SBzrdm2lVOLd+Y55BsCCcynoIz5XOnID0ApptPz2vV2TsV9LRsbFcTJ8lk/QoqazD8WKAefuJRUcVyt9TkW9NU4gmccwt5LtIGlTI1al3cdXhOUA3psHMT/VjxPanRfk+rDAcHXFtg5n3Pb+ItEsWvu/yOdqVih5BEfZVg8WryiVYSUHfcXtc8icJa3u7tQ0ZIfdMhSENOSlPWq/JFeqPRzGx/PvfkoTmbRUgDQ7+Bm/s0icCmXmhjMza3r2cLJSgrOLtz7LCLSknp9iV8qVXoiN2V13uI4fm2eFGHzQEt1DbRx5jHb+xI0eLZu0cbitjxYbaXwhVbcZtGfMJXnQIf+e7hVknUrCmzRYmUDppRBJeXvkuRAhsMdaXGSl2LitP0VztzUMmbs2UffpI1DeiSlzm8BZfVQK9dv2AdvVIWsFsn84xnfBjOJ89rM+nbyJoLjfbOux3g2Xd5WWEey0AXf5oy+9qJl3z/p3o3hwGN8njGvqYnjn5N4e871gZXoO/8Q78LVmqQLGzuNANfF4ynpg=
    guild-id: AgBXYxwuiWZD0uBDIaMMdSZUtKX1mAAtqpLnKVVv61/NODzDAv5rVPqR5ltuMuht0Y5ATpEroLiGRr94WrrteZ2uT73hN5yLPloafSRTWX7TTBvDYVdms8eER4SHykTU1q7XyPPNfZsrUjauJ93KWp+wK/7ClFR+KFM1plj8VCINKEKD76HY3XUQoGlDmEBQAKh+8qfoXMkGKg+ICIM/iKJPGihKdiP8ruqmOYP0/LTm7J2BFzxyRTrw4xDt20vNt6DQLNry3gyHzt1Iz26+/kp+55pexHBKyX3B1WUxUSC5dA++3hpSiGDyj0XM4eyrzWlUFhN8xVCLEb9G4v92WQ2LmJQaruE3N7jXv8KArb+uOjJO2OxaEQ5F78cmqXVRDEzgdw50soHyK4DAlO2w8DpMEA56y9dJxjCoqaKQQv+0LIhBs77sYmWih9e0GspdnnOzHBzU4OKdlk4SLYWbcQOzkFBh7tdv3nhZp08l56Og2RvqFd5ZOqjgIa5dZK2lMhprz8eLMmDWf+NBuapA1DlPeEXcRCSH8cGCq08uhV6VCvCX6tC0hchxm98bUatlYBpG4DSZYiD81530fx9p+L1PcckweTaR1Xo71JqiqpvmicpB13NT5/7Foh/dCKwCc+k0oLkEyIT3e/wOAXt5/2NF7YUASCmP9Y414yqY9BcerwNDx141g6Spjd7ZxRcqgq/NYbmuTaWl9cM3l/lmkif5aM0=
  template:
    metadata:
      name: miha
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
