apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miha
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    discord-token: AgAOuwW/aMG06K8DoYuxyAali5cuL8r2Dm2JBDTcqzfhJO81ypmDG5Llf8kOf8BTJk877NHOeSeqmQxgaDZRHKlmxrmmmFKYNeP7pYd1G0b2upjycgmoOgAA1J39QftWvTjvavudrYBYwU0qCigURkEoJf+aoAmkn3WLYfuzVVyVsH3+tQqQEsqc7HAZF74wkFWs5wnJiCj3O5q3wRgwFvYS9BrvUddV+kyh8JyyuBorR8MTw9+AFneB5qv4ZOEwhOhoJcYFptrO7PrEfNtCuFLuwo0HQxq/a6AXI8PEllfEzh381s7GqWA6OeSH6zI4D/Tz7X2OTdE78p9IKBScMXTH7xwA1rlPOvNRLH/QoMwuzrOvKRdaGs6nG2KBpoXo11hJaSASUVqvQiJlUKaZ7GU8eqHHQwE2z12IBjvUfkMwXQjn0rom995srR2Mp6a2cjCge6oOft0XldwgnaMAXQdnyPMew1kvrXF8l5ozGYOO+928qsp/ur1WN0a1K3vz5LnWNHCBzsa8qrw2/Z/JaT3iMutjvHzG476FkH2965Tb21K+Bwg683scfisroIIAnV2egdSwBSEHOBIvXMMatZTo2BR3ghgBdY/45jsBp28Dg23O4xSxQ9ACK8WIzul1fUoKkZN7g5oF2SRgbXSX6bJI1OMxzfcaGG8jtVLhmTT1FzQJgeaI1MUZ+R4TfSHi9A9yXYbdY7l3TbAkK5BTwF8RwsrBG6K64betSBzBuBOPnIuSZjKIsmrgkSq2qsPReTL4zFEaOd6W2coXRbPeVlA9+f+sVwM3B1k=
    guild-id: AgBM79SlfrJ/QcyVs7L9gMFrvTo8ufD0ezx+rM6Ks8fWjPtOa+2sfMc2JpdSTAev+O/WGVxOnlwbNgUOBMkMJLzYfVLSqNLIChT2AAj/be+ze+Z53DkBZBXB4H8vgPHwxzJvKFN1WDNogMwlT/QkFKkF5tDUYTZWrdUUEkSHmP6Ci68YH88K4ZVCMG3hEzbgiNPevYaLFhsEgOIey/FkfbSNzyKxKrDewxyMaLbwVfO4rTm+o/JAF2H87INw+KyYsKFN+i26jXg7OQfKK71WkfFVREBhdh5Yxv8X1tSOh6lf0WMzbT5hSVG8tPLNhjxT3pEcjromcGHYngK4mZGigSs4AAoTAqOVu92bWhkzsSm8u/JXZSdQLYgSf2y1icG8daguHhgfj1/l+t76Qm7x0UahIqCPTYbSf/RrWYNT7PfLDbNwzqmVKZFtthcetg3AwUSRGZOCIZ7utD3j3i0PR5970s98VtrzDYneEdDXlYiGcX8eplv8Fq1a0gSXu3binhyr8tCyKvZ1yL02z/BUn2LUHma/S72uWbub5O08/A5spdXLWRVXunQsxTJzgswfuCMHIhnoZv5CFFibbLvVdU2EfSkWvbbqkn9GirAafv8sRyFnxnS8R8dGJTdzo8YJ7sETbPFrL7j+IME+IxKkAb0nqwBXKt+bel9oMzFiyUdf56GtiY2+sSrO6XDBhacmwRLF44dg1V7fDi8P0UA+SoxBgm4=
  template:
    metadata:
      name: miha
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
