apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miha
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    discord-token: AgAko15gcgBsjsclfKDbpitWi8ZYxxpjRvYzu2vSx3vQGga+VidrWha3DwVaqbOMPugcn7JVTsYZomAJP300GRgU8VV7L5gDZH5+vVV+aq6XeZgSya36u55fzbTMXcBHYe9Yaz9/gXwC+yC/kijKrx7Bqw77vxe31Niru0tHzT4w7z8Ao24Js2EAngTkOnRe4NQw2EGM5xx4wByUSwnnnObPc3i/glDOwXRMCbi7zApXty/Gop/gmMln9xTLb+aYJhH0Sxivr3d3GXd2gFd7gRX/X/KJl4VxOhz1hj7usUCw9j7lE2mSTfxOlASaVOpsbiEp1ZsPp5OX3wVILLAcCqVNA1o0h0STIQJSKLbiKDETzHYe0rEGc+ZvUs7HmGrGYJL9WtLll4xBnmuOX/icw0jAWMEzNSRWN2jXklbxZC2doU6kG4cExdef6Cc/KzepPY8vmDalBUb1QIjtwGy82/0DntpF5dE5/9ZYh2xEy3eEbRiEMqcoi7Fdf+Lyyiwo7elvqFRDoDbP1LroQVFCefuk3rEr3+Hw3Aw6ZAuHCetOmL9zy/0hDFyzBggxdF521lS/v6gbYspAcyidMiO6fIXQw4TX8FHTYqtDosg/Ngjb/x6Mcha+T9ehGFy1yDBpFcULhlfhm5zosCBqn2mziunQIxMo30x5Ye7nn/O51YY1jErrt4QXONl62V52DLGlWU6l8ITiZDjGgPKq4pzMkQPssJoLfB8Bq51IltSkADQ5Rnf5pSaAKWdbaJaZbLivvTj7nAhQgno3tv5r9c7WSO8c3YQ53JNF6gg=
    guild-id: AgAC/moEj25IEoxWO7Qhj7QVLbbROMj73qN7cNXK7aTK68sgjxR9XpoDNjXmsKFhv/W5FyZWf/f1ysIh5gsVb7ZnscOeY50FIzVRzl6WNlCbqoxMeuO1kk7ndTWW8BH25/efr2JiM4wNjm4SBcnRladxzxGutCKqvW4t0c+mAQhCVwqAF09nFi8v27sqFth5Nd2w9FhDeMN2OxNcC8LHD3NFy2RTOXUERdjfIulDJ1cTe1VWfv/Ymx1/iZofUth7rN7UhvjIjyHEiOOkc5V8gytIWh6KRPYX+LePJBdqBVrnfU4qdJU+liwmJRFgVVnJYtSoPI3s8dGfPB7CBNJzcwxLhQXHSeqS4iIkpUywzCv629eAN2FkpbTmQmzCCOpiTssnDli3yAyIGvhg69gGUZ8ryIt51BPK3CmNSipFo+loTne9ljAUEkfiNkYEEd2Pj08dZy5rp3cOutA+4T0rmz17EPaJgyrtlPHZ7k6YG5NKQ6HZXR0LAq4kaU4cjmN60ulHu5sICBRPK9IY/maaWhg+Q/YQXpmAa0XoVVpFlhqpEYkRiUpOEnJt+RP+A5VjdG7PET4f6Zg9MfDP3jKD2YB6DggyMH6lr3zcO/2/1dYCKnQiS53EdjfRXWBS/k4HyZz/Iwtl7aErNmtNtdetk7bhq6Sy3t/DifnYDeDxTxnZbHYvTDMweNIAhImnJbycpJrpM4O1fO9bTAjlYkRSkZPgSqk=
  template:
    metadata:
      name: miha
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
