apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 6h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      # Number of retries that should be attempted on failures before bailing, a negative integer equals to unlimited retries
      retries: -1
  chart:
    spec:
      chart: reflector
      version: "9.x.x"
      sourceRef:
        kind: HelmRepository
        name: reflector-repo
      interval: 12h
