apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: 3.x.x
      sourceRef:
        kind: HelmRepository
        name: secret-generator-repo
      interval: 12h
  # https://artifacthub.io/packages/helm/kubernetes-replicator/kubernetes-secret-generator?modal=values
  values:
