apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 6h
  chart:
    spec:
      chart: external-dns
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns-repo
      interval: 12h
  # https://github.com/bitnami/charts/blob/main/bitnami/external-dns/values.yaml
  values: