apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: external-dns
  # https://github.com/bitnami/charts/blob/main/bitnami/external-dns/values.yaml
  values:
    metrics:
      enabled: false